### ISSUE TITLE
Can't clone repository

### ISSUE THREAD

**Issue by ignaciovidalfranco** [apertium/apertium-all#2]
The following git command in the README.md file:

`git clone --recurse-submodules --shallow-submodules --depth 1 git@github.com:apertium/apertium-tools.git`

does not clone the whole apertium repository and exits with errors:
```

Clonning in 'apertium-all'...
git@github.com: Permission denied (publickey).
fatal: Can't read from repote repository
```

**Comment by sushain97** [comment]
I don't believe this is an issue with this repository. You'll need to set up SSH authentication with GitHub. I suggest following these instructions: https://help.github.com/articles/connecting-to-github-with-ssh/.

**Comment by unhammer** [comment]
Doesn't 

`git clone --recurse-submodules --shallow-submodules --depth 1 https://github.com/apertium/apertium-all.git`

work without write access?

**Comment by sushain97** [comment]
No, the submodules are SSH. SSH doesn't require write access though? Tino and I discussed it was between inconveniencing devs and casual users and since this repo isn't really meant for casual users, I picked the latter.

**Comment by ignaciovidalfranco** [comment]
Oh, I see. 
Then, is there a suitable way to clone apertium meant for casual users?
I mean, that's what I would have expected.

Thank you for clarifying this, anyway.

**Comment by sushain97** [comment]
Well, I suppose there isn't because I haven't foreseen any casual users interested in cloning everything. The whole tree is probably well over 8GB at this point and with full history > 30GB :)

What are you looking to do with the whole tree?
