### ISSUE TITLE
Where is .autogen.sh in the home folder?

### ISSUE THREAD

**Issue by gusbemacbe** [apertium/apertium-all#3]
Hi,

You suggest us to run at the wiki:

```
./autogen.sh --with-lang1=../apertium-XXX --with-lang2=../apertium-YYY
make -j
```

But there is no` ./autogen.sh i`n the home folder. Are you referring to ` ./apertium-XXX/autogen.sh` and `./apertium-YYY/autogen.sh`?

**Comment by sushain97** [comment]
> Are you referring to ./apertium-XXX/autogen.sh and ./apertium-YYY/autogen.sh?

`./apertium-XXX-YYY/autogen.sh`.

**Comment by gusbemacbe** [comment]
It gave a warning:

`autoreconf: 'configure.ac' or 'configure.in' is required`

**Comment by gusbemacbe** [comment]
I checked the folder apertium-eng-port and I saw I have configure.ac, but it still gave the same error.

**Comment by gusbemacbe** [comment]
I fixed it. I had to cd and it worked. But when I ran `echo house | apertium . -d eng-por`, it gave a warning: 

`Error: Directory './modes' does not exist.`

**Comment by sushain97** [comment]
What folder are you running it in and did you finish the remainder of the build process?

**Comment by gusbemacbe** [comment]
The folder `apertium-eng-por`

**Comment by sushain97** [comment]
Did you run `make`?

**Comment by gusbemacbe** [comment]
Yes, but I made a clean install and fixed it. BUt it gave an error:

```
if test -n "$modes"; then mv $modes modes/; fi
final@inconditional 123 6032
main@standard 23885 48030
contractions@standard 434 571
Warning: section had no final state after trimming! Skipping it ...
final@inconditional 110 2975
main@standard 64691 123997
gus@gus:~/apertium-eng
```

**Comment by sushain97** [comment]
Where's the error?

**Comment by gusbemacbe** [comment]
Ah, I forgot of the error. Here is the error:

```
~/apertium-eng-por$ echo 'house' | apertium eng-por
Error: Mode eng-por does not exist. Try one of:
  deu-eng
  en-es
  en-fr
  eng-deu
  es-en
  es-en_US
  fr-en
  fr-en_US
```
I added `-d` but it didn't get a result:

```
~/apertium-eng-por$ echo 'house' | apertium -d eng-por
USAGE: apertium [-d datadir] [-f format] [-u] <direction> [in [out]]
 -d datadir       directory of linguistic data
 -f format        one of: txt (default), html, rtf, odt, docx, wxml, xlsx, pptx,
                  xpresstag, html-noent, latex, latex-raw, line
 -a               display ambiguity
 -u               don't display marks '*' for unknown words
 -n               don't insert period before possible sentence-ends
 -m memory.tmx    use a translation memory to recycle translations
 -o direction     translation direction using the translation memory,
                  by default 'direction' is used instead
 -l               lists the available translation directions and exits
 direction        typically, LANG1-LANG2, but see modes.xml in language data
 in               input file (stdin by default)
 out              output file (stdout by default)
```
Then I added `.` with `-d` (`echo 'house' | apertium -d . eng-por`), it crashed.

With `.` and without `-d` (`echo 'house' | apertium . eng-por`), it gave an error:  `Error: file 'eng-por' not found.`

**Comment by sushain97** [comment]
> Then I added . with -d (echo 'house' | apertium -d . eng-por), it crashed.

This is the correct usage. _How_ did it crash?

**Comment by gusbemacbe** [comment]
![crash](https://user-images.githubusercontent.com/2257024/39977021-6eed8732-570d-11e8-8a77-751b1dd54fc1.gif)

**Comment by sushain97** [comment]
I don't see a crash. However, if `echo 'house' | apertium -d . en-es` works, then I suggest filing an issue with the `eng-por` maintainers.

**Comment by gusbemacbe** [comment]
I have apertium and apertium-en-es installed and I tested this command, it also gave an error:

![image](https://user-images.githubusercontent.com/2257024/39977160-56b16ec6-570e-11e8-95ac-2a7b20eaea5b.png)

unless I ran the command and it worked:

![image](https://user-images.githubusercontent.com/2257024/39977174-73706990-570e-11e8-868e-91d93a83454f.png)

**Comment by gusbemacbe** [comment]
I also tested https://github.com/apertium/apertium-en-pt/, but it gave an error that the file configure does not exist.

**Comment by sushain97** [comment]
Ah, my apologies, I meant `echo 'house' | apertium en-es`. Since that works, I suggest you file an issue in the pair repo for pair specific issues. You're more likely to get help/get a bug fixed from the appropriate people there (or visit #apertium).

**Comment by gusbemacbe** [comment]
But which repository is adequate for reporting the bug of Eng-Port? Is it https://github.com/apertium/apertium-en-pt/?

**Comment by sushain97** [comment]
Where did you get `eng-por`...?

**Comment by gusbemacbe** [comment]
Here is the http://wiki.apertium.org/wiki/How_to_bootstrap_a_new_pair.

**Comment by sushain97** [comment]
If you created `eng-por` yourself using `apertium-init` and it didn't work, then `apertium-init` is probably at fault.

**Comment by gusbemacbe** [comment]
Yes, I ran `apertium-init.`

**Comment by TinoDidriksen** [comment]
@gusbemacbe, please don't discuss at such lengths in a bug report - that's what IRC is for: Join [irc.freenode.net #apertium](https://webchat.freenode.net/?channels=apertium) and ask there. Or ask the [apertium-stuff mailing list](http://wiki.apertium.org/wiki/Contact).

And beyond that, you don't need to bootstrap a pair that already exists. That said, there is an [endless loop bug in apertium-init](https://github.com/apertium/apertium-init/issues/31) with regards to handling of .prob files, which is what you're seeing.

Closing this issue, since it's in the wrong place.
